window.opacity = 1.0

[colors.bright]
black = "0x555555"
blue = "0x5555ff"
cyan = "0x55ffff"
green = "0x55ff55"
magenta = "0xff55ff"
red = "0xff5555"
white = "0xffffff"
yellow = "0xffff55"

[colors.cursor]
cursor = "0x9cabca"
text = "0x000000"

[colors.normal]
black = "0x000000"
blue = "0x0000ff"
cyan = "0x00ffff"
green = "0x00ff00"
magenta = "0xff00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xffff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[colors.selection]
background = "0x4e5579"
text = "0xffffff"

[font]
size = 12

[font.normal]
family = "FiraCode"
style = "Regular"

[general]
live_config_reload = true
